# Inspect extracted player statistics

Each league uses its own latest saved date. Zero is filled data; NULL and blank
strings are missing. Players normally have data only for positions they played.
Historical snapshots can have empty grouped columns. `P` and `DH` source splits
are included in inspection when stored, although defender reports exclude them.

In [1]:
import sqlite3
from contextlib import closing
from pathlib import Path

import pandas as pd

from mlb_airflow_data_pipeline.db_utils import read_player_stats
from mlb_airflow_data_pipeline.statsapi_parameters_script import (
    DATA_FILE_LOCATION,
    FIELDING_POSITIONS,
    PLAYER_INFORMATION,
    expected_output_columns,
)

pd.set_option("display.max_rows", None)

# Edit this path to inspect a different database.
database_path = Path(DATA_FILE_LOCATION) / "mlb_data.db"

## Load the schema and latest rows

This cell reads one consistent view of the database. Rerun it to refresh the data
following another extraction. No database file is created if the path is wrong.

In [2]:
with closing(
    sqlite3.connect(database_path.resolve().as_uri() + "?mode=ro", uri=True)
) as connection:
    schema = pd.read_sql_query('PRAGMA table_info("player_stats")', connection)
    latest_snapshots = pd.read_sql_query(
        "SELECT league_name, MAX(date) AS date FROM player_stats GROUP BY league_name",
        connection,
    )
    latest_players = pd.concat(
        [
            read_player_stats(connection, league_name, execution_date)
            for league_name, execution_date in latest_snapshots.itertuples(
                index=False, name=None
            )
        ],
        ignore_index=True,
    ).sort_values(["league_name", "team_id", "player_id"])

snapshot_counts = (
    latest_players.groupby(["league_name", "date"])
    .size()
    .rename("total_rows")
    .reset_index()
)
snapshot_counts

       league_name        date  total_rows
0  american_league  2026-10-11         535
1  national_league  2026-10-10         556

## Check the new schema

The first table counts grouped columns. The next lists their names and SQLite
types and whether they are supported by the extraction schema; edit `schema_prefix` to inspect hitting, pitching, or a particular position.
Columns are added when extraction encounters them, so not every possible source
statistic must exist in the database.

In [10]:
grouped_schema = schema.loc[
    schema["name"].str.startswith(("hitting_", "pitching_", "fielding_")),
    ["name", "type"],
].sort_values("name")
grouped_schema["supported"] = grouped_schema["name"].isin(expected_output_columns())
grouped_schema[~grouped_schema["supported"]]

Empty DataFrame
Columns: [name, type, supported]
Index: []

In [4]:
schema_counts = (
    grouped_schema["name"]
    .str.split("_", n=1)
    .str[0]
    .value_counts()
    .reindex(["hitting", "pitching", "fielding"], fill_value=0)
    .rename_axis("group")
    .rename("columns")
    .reset_index()
)
schema_counts

      group  columns
0   hitting       34
1  pitching       62
2  fielding      159

## Check filled fielding columns

Coverage shows the number of populated rows for **every stored fielding column**,
using each league's latest snapshot. The following position summary counts players
with any populated fielding statistic at that position. Missing positions remain
visible with zero rows; sparse values alone do not indicate an extraction failure.

In [5]:
fielding_columns = grouped_schema.loc[
    grouped_schema["name"].str.startswith("fielding_"), "name"
].tolist()
fielding_values = latest_players[fielding_columns].astype("string")
filled = fielding_values.notna() & fielding_values.apply(
    lambda column: column.str.strip().ne("")
)
snapshot_keys = [latest_players["league_name"], latest_players["date"]]
fielding_counts = filled.groupby(snapshot_keys).sum()
coverage = (
    fielding_counts.rename_axis(columns="column")
    .stack()
    .rename("filled_rows")
    .reset_index()
    .merge(snapshot_counts, on=["league_name", "date"])
)
coverage

,league_name,date,column,filled_rows,total_rows
0,american_league,2026-10-11,fielding_1B_age,65,535
1,american_league,2026-10-11,fielding_1B_assists,65,535
2,american_league,2026-10-11,fielding_1B_chances,65,535
3,american_league,2026-10-11,fielding_1B_doublePlays,65,535
4,american_league,2026-10-11,fielding_1B_errors,65,535
5,american_league,2026-10-11,fielding_1B_fielding,65,535
6,american_league,2026-10-11,fielding_1B_games,65,535
7,american_league,2026-10-11,fielding_1B_gamesPlayed,65,535
8,american_league,2026-10-11,fielding_1B_gamesStarted,65,535
9,american_league,2026-10-11,fielding_1B_innings,65,535
10,american_league,2026-10-11,fielding_1B_putOuts,65,535
11,american_league,2026-10-11,fielding_1B_rangeFactorPer9Inn,65,535
12,american_league,2026-10-11,fielding_1B_rangeFactorPerGame,65,535
13,american_league,2026-10-11,fielding_1B_throwingErrors,65,535
14,american_league,2026-10-11,fielding_1B_triplePlays,65,535
15,american_league,2026-10-11,fielding_2B_age,75,535
16,american_league,2026-10-11,fielding_2B_assists,75,535
17,american_league,2026-10-11,fielding_2B_chances,75,535
18,american_league,2026-10-11,fielding_2B_doublePlays,75,535
19,american_league,2026-10-11,fielding_2B_errors,75,535
20,american_league,2026-10-11,fielding_2B_fielding,75,535
21,american_league,2026-10-11,fielding_2B_games,75,535
22,american_league,2026-10-11,fielding_2B_gamesPlayed,75,535
23,american_league,2026-10-11,fielding_2B_gamesStarted,75,535
24,american_league,2026-10-11,fielding_2B_innings,75,535
25,american_league,2026-10-11,fielding_2B_putOuts,75,535
26,american_league,2026-10-11,fielding_2B_rangeFactorPer9Inn,75,535
27,american_league,2026-10-11,fielding_2B_rangeFactorPerGame,75,535
28,american_league,2026-10-11,fielding_2B_throwingErrors,75,535
29,american_league,2026-10-11,fielding_2B_triplePlays,75,535
30,american_league,2026-10-11,fielding_3B_age,76,535
31,american_league,2026-10-11,fielding_3B_assists,76,535
32,american_league,2026-10-11,fielding_3B_chances,76,535
33,american_league,2026-10-11,fielding_3B_doublePlays,76,535
34,american_league,2026-10-11,fielding_3B_errors,76,535
35,american_league,2026-10-11,fielding_3B_fielding,76,535
36,american_league,2026-10-11,fielding_3B_games,76,535
37,american_league,2026-10-11,fielding_3B_gamesPlayed,76,535
38,american_league,2026-10-11,fielding_3B_gamesStarted,76,535
39,american_league,2026-10-11,fielding_3B_innings,76,535
40,american_league,2026-10-11,fielding_3B_putOuts,76,535
41,american_league,2026-10-11,fielding_3B_rangeFactorPer9Inn,76,535
42,american_league,2026-10-11,fielding_3B_rangeFactorPerGame,76,535
43,american_league,2026-10-11,fielding_3B_throwingErrors,76,535
44,american_league,2026-10-11,fielding_3B_triplePlays,76,535
45,american_league,2026-10-11,fielding_CF_age,72,535
46,american_league,2026-10-11,fielding_CF_assists,72,535
47,american_league,2026-10-11,fielding_CF_chances,72,535
48,american_league,2026-10-11,fielding_CF_doublePlays,72,535
49,american_league,2026-10-11,fielding_CF_errors,72,535
50,american_league,2026-10-11,fielding_CF_fielding,72,535
51,american_league,2026-10-11,fielding_CF_games,72,535
52,american_league,2026-10-11,fielding_CF_gamesPlayed,72,535
53,american_league,2026-10-11,fielding_CF_gamesStarted,72,535
54,american_league,2026-10-11,fielding_CF_innings,72,535
55,american_league,2026-10-11,fielding_CF_putOuts,72,535
56,american_league,2026-10-11,fielding_CF_rangeFactorPer9Inn,72,535
57,american_league,2026-10-11,fielding_CF_rangeFactorPerGame,72,535
58,american_league,2026-10-11,fielding_CF_throwingErrors,72,535
59,american_league,2026-10-11,fielding_CF_triplePlays,72,535
60,american_league,2026-10-11,fielding_C_age,43,535
61,american_league,2026-10-11,fielding_C_assists,43,535
62,american_league,2026-10-11,fielding_C_catcherERA,43,535
63,american_league,2026-10-11,fielding_C_catchersInterference,43,535
64,american_league,2026-10-11,fielding_C_caughtStealing,43,535
65,american_league,2026-10-11,fielding_C_caughtStealingPercentage,43,535
66,american_league,2026-10-11,fielding_C_chances,43,535
67,american_league,2026-10-11,fielding_C_doublePlays,43,535
68,american_league,2026-10-11,fielding_C_errors,43,535
69,american_league,2026-10-11,fielding_C_fielding,43,535
70,american_league,2026-10-11,fielding_C_games,43,535
71,american_league,2026-10-11,fielding_C_gamesPlayed,43,535
72,american_league,2026-10-11,fielding_C_gamesStarted,43,535
73,american_league,2026-10-11,fielding_C_innings,43,535
74,american_league,2026-10-11,fielding_C_passedBall,43,535
75,american_league,2026-10-11,fielding_C_pickoffs,43,535
76,american_league,2026-10-11,fielding_C_putOuts,43,535
77,american_league,2026-10-11,fielding_C_rangeFactorPer9Inn,43,535
78,american_league,2026-10-11,fielding_C_rangeFactorPerGame,43,535
79,american_league,2026-10-11,fielding_C_stolenBasePercentage,43,535
80,american_league,2026-10-11,fielding_C_stolenBases,43,535
81,american_league,2026-10-11,fielding_C_throwingErrors,43,535
82,american_league,2026-10-11,fielding_C_triplePlays,43,535
83,american_league,2026-10-11,fielding_C_wildPitches,43,535
84,american_league,2026-10-11,fielding_DH_age,184,535
85,american_league,2026-10-11,fielding_DH_assists,184,535
86,american_league,2026-10-11,fielding_DH_chances,184,535
87,american_league,2026-10-11,fielding_DH_doublePlays,184,535
88,american_league,2026-10-11,fielding_DH_errors,184,535
89,american_league,2026-10-11,fielding_DH_fielding,184,535
90,american_league,2026-10-11,fielding_DH_games,184,535
91,american_league,2026-10-11,fielding_DH_gamesPlayed,184,535
92,american_league,2026-10-11,fielding_DH_gamesStarted,184,535
93,american_league,2026-10-11,fielding_DH_innings,184,535
94,american_league,2026-10-11,fielding_DH_putOuts,184,535
95,american_league,2026-10-11,fielding_DH_rangeFactorPer9Inn,184,535
96,american_league,2026-10-11,fielding_DH_rangeFactorPerGame,184,535
97,american_league,2026-10-11,fielding_DH_throwingErrors,184,535
98,american_league,2026-10-11,fielding_DH_triplePlays,184,535
99,american_league,2026-10-11,fielding_LF_age,103,535
100,american_league,2026-10-11,fielding_LF_assists,103,535
101,american_league,2026-10-11,fielding_LF_chances,103,535
102,american_league,2026-10-11,fielding_LF_doublePlays,103,535
103,american_league,2026-10-11,fielding_LF_errors,103,535
104,american_league,2026-10-11,fielding_LF_fielding,103,535
105,american_league,2026-10-11,fielding_LF_games,103,535
106,american_league,2026-10-11,fielding_LF_gamesPlayed,103,535
107,american_league,2026-10-11,fielding_LF_gamesStarted,103,535
108,american_league,2026-10-11,fielding_LF_innings,103,535
109,american_league,2026-10-11,fielding_LF_putOuts,103,535
110,american_league,2026-10-11,fielding_LF_rangeFactorPer9Inn,103,535
111,american_league,2026-10-11,fielding_LF_rangeFactorPerGame,103,535
112,american_league,2026-10-11,fielding_LF_throwingErrors,103,535
113,american_league,2026-10-11,fielding_LF_triplePlays,103,535
114,american_league,2026-10-11,fielding_P_age,294,535
115,american_league,2026-10-11,fielding_P_assists,294,535
116,american_league,2026-10-11,fielding_P_chances,294,535
117,american_league,2026-10-11,fielding_P_doublePlays,294,535
118,american_league,2026-10-11,fielding_P_errors,294,535
119,american_league,2026-10-11,fielding_P_fielding,294,535
120,american_league,2026-10-11,fielding_P_games,294,535
121,american_league,2026-10-11,fielding_P_gamesPlayed,294,535
122,american_league,2026-10-11,fielding_P_gamesStarted,294,535
123,american_league,2026-10-11,fielding_P_innings,294,535
124,american_league,2026-10-11,fielding_P_putOuts,294,535
125,american_league,2026-10-11,fielding_P_rangeFactorPer9Inn,294,535
126,american_league,2026-10-11,fielding_P_rangeFactorPerGame,294,535
127,american_league,2026-10-11,fielding_P_throwingErrors,294,535
128,american_league,2026-10-11,fielding_P_triplePlays,294,535
129,american_league,2026-10-11,fielding_RF_age,88,535
130,american_league,2026-10-11,fielding_RF_assists,88,535
131,american_league,2026-10-11,fielding_RF_chances,88,535
132,american_league,2026-10-11,fielding_RF_doublePlays,88,535
133,american_league,2026-10-11,fielding_RF_errors,88,535
134,american_league,2026-10-11,fielding_RF_fielding,88,535
135,american_league,2026-10-11,fielding_RF_games,88,535
136,american_league,2026-10-11,fielding_RF_gamesPlayed,88,535
137,american_league,2026-10-11,fielding_RF_gamesStarted,88,535
138,american_league,2026-10-11,fielding_RF_innings,88,535
139,american_league,2026-10-11,fielding_RF_putOuts,88,535
140,american_league,2026-10-11,fielding_RF_rangeFactorPer9Inn,88,535
141,american_league,2026-10-11,fielding_RF_rangeFactorPerGame,88,535
142,american_league,2026-10-11,fielding_RF_throwingErrors,88,535
143,american_league,2026-10-11,fielding_RF_triplePlays,88,535
144,american_league,2026-10-11,fielding_SS_age,61,535
145,american_league,2026-10-11,fielding_SS_assists,61,535
146,american_league,2026-10-11,fielding_SS_chances,61,535
147,american_league,2026-10-11,fielding_SS_doublePlays,61,535
148,american_league,2026-10-11,fielding_SS_errors,61,535
149,american_league,2026-10-11,fielding_SS_fielding,61,535
150,american_league,2026-10-11,fielding_SS_games,61,535
151,american_league,2026-10-11,fielding_SS_gamesPlayed,61,535
152,american_league,2026-10-11,fielding_SS_gamesStarted,61,535
153,american_league,2026-10-11,fielding_SS_innings,61,535
154,american_league,2026-10-11,fielding_SS_putOuts,61,535
155,american_league,2026-10-11,fielding_SS_rangeFactorPer9Inn,61,535
156,american_league,2026-10-11,fielding_SS_rangeFactorPerGame,61,535
157,american_league,2026-10-11,fielding_SS_throwingErrors,61,535
158,american_league,2026-10-11,fielding_SS_triplePlays,61,535
159,national_league,2026-10-10,fielding_1B_age,0,556
160,national_league,2026-10-10,fielding_1B_assists,0,556
161,national_league,2026-10-10,fielding_1B_chances,0,556
162,national_league,2026-10-10,fielding_1B_doublePlays,0,556
163,national_league,2026-10-10,fielding_1B_errors,0,556
164,national_league,2026-10-10,fielding_1B_fielding,0,556
165,national_league,2026-10-10,fielding_1B_games,0,556
166,national_league,2026-10-10,fielding_1B_gamesPlayed,0,556
167,national_league,2026-10-10,fielding_1B_gamesStarted,0,556
168,national_league,2026-10-10,fielding_1B_innings,0,556
169,national_league,2026-10-10,fielding_1B_putOuts,0,556
170,national_league,2026-10-10,fielding_1B_rangeFactorPer9Inn,0,556
171,national_league,2026-10-10,fielding_1B_rangeFactorPerGame,0,556
172,national_league,2026-10-10,fielding_1B_throwingErrors,0,556
173,national_league,2026-10-10,fielding_1B_triplePlays,0,556
174,national_league,2026-10-10,fielding_2B_age,0,556
175,national_league,2026-10-10,fielding_2B_assists,0,556
176,national_league,2026-10-10,fielding_2B_chances,0,556
177,national_league,2026-10-10,fielding_2B_doublePlays,0,556
178,national_league,2026-10-10,fielding_2B_errors,0,556
179,national_league,2026-10-10,fielding_2B_fielding,0,556
180,national_league,2026-10-10,fielding_2B_games,0,556
181,national_league,2026-10-10,fielding_2B_gamesPlayed,0,556
182,national_league,2026-10-10,fielding_2B_gamesStarted,0,556
183,national_league,2026-10-10,fielding_2B_innings,0,556
184,national_league,2026-10-10,fielding_2B_putOuts,0,556
185,national_league,2026-10-10,fielding_2B_rangeFactorPer9Inn,0,556
186,national_league,2026-10-10,fielding_2B_rangeFactorPerGame,0,556
187,national_league,2026-10-10,fielding_2B_throwingErrors,0,556
188,national_league,2026-10-10,fielding_2B_triplePlays,0,556
189,national_league,2026-10-10,fielding_3B_age,0,556
190,national_league,2026-10-10,fielding_3B_assists,0,556
191,national_league,2026-10-10,fielding_3B_chances,0,556
192,national_league,2026-10-10,fielding_3B_doublePlays,0,556
193,national_league,2026-10-10,fielding_3B_errors,0,556
194,national_league,2026-10-10,fielding_3B_fielding,0,556
195,national_league,2026-10-10,fielding_3B_games,0,556
196,national_league,2026-10-10,fielding_3B_gamesPlayed,0,556
197,national_league,2026-10-10,fielding_3B_gamesStarted,0,556
198,national_league,2026-10-10,fielding_3B_innings,0,556
199,national_league,2026-10-10,fielding_3B_putOuts,0,556
200,national_league,2026-10-10,fielding_3B_rangeFactorPer9Inn,0,556
201,national_league,2026-10-10,fielding_3B_rangeFactorPerGame,0,556
202,national_league,2026-10-10,fielding_3B_throwingErrors,0,556
203,national_league,2026-10-10,fielding_3B_triplePlays,0,556
204,national_league,2026-10-10,fielding_CF_age,0,556
205,national_league,2026-10-10,fielding_CF_assists,0,556
206,national_league,2026-10-10,fielding_CF_chances,0,556
207,national_league,2026-10-10,fielding_CF_doublePlays,0,556
208,national_league,2026-10-10,fielding_CF_errors,0,556
209,national_league,2026-10-10,fielding_CF_fielding,0,556
210,national_league,2026-10-10,fielding_CF_games,0,556
211,national_league,2026-10-10,fielding_CF_gamesPlayed,0,556
212,national_league,2026-10-10,fielding_CF_gamesStarted,0,556
213,national_league,2026-10-10,fielding_CF_innings,0,556
214,national_league,2026-10-10,fielding_CF_putOuts,0,556
215,national_league,2026-10-10,fielding_CF_rangeFactorPer9Inn,0,556
216,national_league,2026-10-10,fielding_CF_rangeFactorPerGame,0,556
217,national_league,2026-10-10,fielding_CF_throwingErrors,0,556
218,national_league,2026-10-10,fielding_CF_triplePlays,0,556
219,national_league,2026-10-10,fielding_C_age,0,556
220,national_league,2026-10-10,fielding_C_assists,0,556
221,national_league,2026-10-10,fielding_C_catcherERA,0,556
222,national_league,2026-10-10,fielding_C_catchersInterference,0,556
223,national_league,2026-10-10,fielding_C_caughtStealing,0,556
224,national_league,2026-10-10,fielding_C_caughtStealingPercentage,0,556
225,national_league,2026-10-10,fielding_C_chances,0,556
226,national_league,2026-10-10,fielding_C_doublePlays,0,556
227,national_league,2026-10-10,fielding_C_errors,0,556
228,national_league,2026-10-10,fielding_C_fielding,0,556
229,national_league,2026-10-10,fielding_C_games,0,556
230,national_league,2026-10-10,fielding_C_gamesPlayed,0,556
231,national_league,2026-10-10,fielding_C_gamesStarted,0,556
232,national_league,2026-10-10,fielding_C_innings,0,556
233,national_league,2026-10-10,fielding_C_passedBall,0,556
234,national_league,2026-10-10,fielding_C_pickoffs,0,556
235,national_league,2026-10-10,fielding_C_putOuts,0,556
236,national_league,2026-10-10,fielding_C_rangeFactorPer9Inn,0,556
237,national_league,2026-10-10,fielding_C_rangeFactorPerGame,0,556
238,national_league,2026-10-10,fielding_C_stolenBasePercentage,0,556
239,national_league,2026-10-10,fielding_C_stolenBases,0,556
240,national_league,2026-10-10,fielding_C_throwingErrors,0,556
241,national_league,2026-10-10,fielding_C_triplePlays,0,556
242,national_league,2026-10-10,fielding_C_wildPitches,0,556
243,national_league,2026-10-10,fielding_DH_age,0,556
244,national_league,2026-10-10,fielding_DH_assists,0,556
245,national_league,2026-10-10,fielding_DH_chances,0,556
246,national_league,2026-10-10,fielding_DH_doublePlays,0,556
247,national_league,2026-10-10,fielding_DH_errors,0,556
248,national_league,2026-10-10,fielding_DH_fielding,0,556
249,national_league,2026-10-10,fielding_DH_games,0,556
250,national_league,2026-10-10,fielding_DH_gamesPlayed,0,556
251,national_league,2026-10-10,fielding_DH_gamesStarted,0,556
252,national_league,2026-10-10,fielding_DH_innings,0,556
253,national_league,2026-10-10,fielding_DH_putOuts,0,556
254,national_league,2026-10-10,fielding_DH_rangeFactorPer9Inn,0,556
255,national_league,2026-10-10,fielding_DH_rangeFactorPerGame,0,556
256,national_league,2026-10-10,fielding_DH_throwingErrors,0,556
257,national_league,2026-10-10,fielding_DH_triplePlays,0,556
258,national_league,2026-10-10,fielding_LF_age,0,556
259,national_league,2026-10-10,fielding_LF_assists,0,556
260,national_league,2026-10-10,fielding_LF_chances,0,556
261,national_league,2026-10-10,fielding_LF_doublePlays,0,556
262,national_league,2026-10-10,fielding_LF_errors,0,556
263,national_league,2026-10-10,fielding_LF_fielding,0,556
264,national_league,2026-10-10,fielding_LF_games,0,556
265,national_league,2026-10-10,fielding_LF_gamesPlayed,0,556
266,national_league,2026-10-10,fielding_LF_gamesStarted,0,556
267,national_league,2026-10-10,fielding_LF_innings,0,556
268,national_league,2026-10-10,fielding_LF_putOuts,0,556
269,national_league,2026-10-10,fielding_LF_rangeFactorPer9Inn,0,556
270,national_league,2026-10-10,fielding_LF_rangeFactorPerGame,0,556
271,national_league,2026-10-10,fielding_LF_throwingErrors,0,556
272,national_league,2026-10-10,fielding_LF_triplePlays,0,556
273,national_league,2026-10-10,fielding_P_age,0,556
274,national_league,2026-10-10,fielding_P_assists,0,556
275,national_league,2026-10-10,fielding_P_chances,0,556
276,national_league,2026-10-10,fielding_P_doublePlays,0,556
277,national_league,2026-10-10,fielding_P_errors,0,556
278,national_league,2026-10-10,fielding_P_fielding,0,556
279,national_league,2026-10-10,fielding_P_games,0,556
280,national_league,2026-10-10,fielding_P_gamesPlayed,0,556
281,national_league,2026-10-10,fielding_P_gamesStarted,0,556
282,national_league,2026-10-10,fielding_P_innings,0,556
283,national_league,2026-10-10,fielding_P_putOuts,0,556
284,national_league,2026-10-10,fielding_P_rangeFactorPer9Inn,0,556
285,national_league,2026-10-10,fielding_P_rangeFactorPerGame,0,556
286,national_league,2026-10-10,fielding_P_throwingErrors,0,556
287,national_league,2026-10-10,fielding_P_triplePlays,0,556
288,national_league,2026-10-10,fielding_RF_age,0,556
289,national_league,2026-10-10,fielding_RF_assists,0,556
290,national_league,2026-10-10,fielding_RF_chances,0,556
291,national_league,2026-10-10,fielding_RF_doublePlays,0,556
292,national_league,2026-10-10,fielding_RF_errors,0,556
293,national_league,2026-10-10,fielding_RF_fielding,0,556
294,national_league,2026-10-10,fielding_RF_games,0,556
295,national_league,2026-10-10,fielding_RF_gamesPlayed,0,556
296,national_league,2026-10-10,fielding_RF_gamesStarted,0,556
297,national_league,2026-10-10,fielding_RF_innings,0,556
298,national_league,2026-10-10,fielding_RF_putOuts,0,556
299,national_league,2026-10-10,fielding_RF_rangeFactorPer9Inn,0,556
300,national_league,2026-10-10,fielding_RF_rangeFactorPerGame,0,556
301,national_league,2026-10-10,fielding_RF_throwingErrors,0,556
302,national_league,2026-10-10,fielding_RF_triplePlays,0,556
303,national_league,2026-10-10,fielding_SS_age,0,556
304,national_league,2026-10-10,fielding_SS_assists,0,556
305,national_league,2026-10-10,fielding_SS_chances,0,556
306,national_league,2026-10-10,fielding_SS_doublePlays,0,556
307,national_league,2026-10-10,fielding_SS_errors,0,556
308,national_league,2026-10-10,fielding_SS_fielding,0,556
309,national_league,2026-10-10,fielding_SS_games,0,556
310,national_league,2026-10-10,fielding_SS_gamesPlayed,0,556
311,national_league,2026-10-10,fielding_SS_gamesStarted,0,556
312,national_league,2026-10-10,fielding_SS_innings,0,556
313,national_league,2026-10-10,fielding_SS_putOuts,0,556
314,national_league,2026-10-10,fielding_SS_rangeFactorPer9Inn,0,556
315,national_league,2026-10-10,fielding_SS_rangeFactorPerGame,0,556
316,national_league,2026-10-10,fielding_SS_throwingErrors,0,556
317,national_league,2026-10-10,fielding_SS_triplePlays,0,556

In [6]:
position_flags = pd.DataFrame(index=latest_players.index)
for position in FIELDING_POSITIONS:
    columns = [
        column
        for column in fielding_columns
        if column.startswith(f"fielding_{position}_")
    ]
    position_flags[position] = filled[columns].any(axis=1)
position_coverage = position_flags.groupby(snapshot_keys).sum()
position_coverage

                              P   C  1B  2B  3B  SS   LF  CF  RF   DH
league_name     date
american_league 2026-10-11  294  43  65  75  76  61  103  72  88  184
national_league 2026-10-10    0   0   0   0   0   0    0   0   0    0

## Inspect individual players

Edit `league_name`, `position`, and `sample_limit`, then rerun this cell. All stored
statistics for the chosen position are included, so missing values can be checked
alongside player identity. `latest_players`, `coverage`, and `schema` remain
available for additional queries in new cells.

In [7]:
league_name = "american_league"
position = "C"
sample_limit = 10

position_columns = [
    column for column in fielding_columns if column.startswith(f"fielding_{position}_")
]
sample_rows = latest_players["league_name"].eq(league_name) & filled[
    position_columns
].any(axis=1)
player_samples = latest_players.loc[
    sample_rows,
    ["league_name", "date", "player_id"] + PLAYER_INFORMATION + position_columns,
].head(sample_limit)
player_samples

,league_name,date,player_id,playername,team_id,fielding_C_age,fielding_C_assists,fielding_C_catcherERA,fielding_C_catchersInterference,fielding_C_caughtStealing,...,fielding_C_passedBall,fielding_C_pickoffs,fielding_C_putOuts,fielding_C_rangeFactorPer9Inn,fielding_C_rangeFactorPerGame,fielding_C_stolenBasePercentage,fielding_C_stolenBases,fielding_C_throwingErrors,fielding_C_triplePlays,fielding_C_wildPitches
0,american_league,2026-10-11,518595,Vaughn Grissom,108,37,11,4.17,0,6,...,0,0,221,9.90,8.29,.727,16,0,0,9
3,american_league,2026-10-11,623168,Moisés Ballesteros,108,35,27,4.09,2,19,...,4,0,540,9.85,7.77,.689,42,2,0,14
7,american_league,2026-10-11,665861,Zach Neto,108,27,6,3.74,2,1,...,0,0,145,9.44,6.29,.938,15,1,0,5
18,american_league,2026-10-11,682515,Yusei Kikuchi,108,30,1,9.00,0,0,...,0,0,7,4.50,4.00,1.000,2,0,0,1
27,american_league,2026-10-11,694208,Trevor Martin,108,22,9,4.39,0,4,...,3,0,182,8.86,6.59,.826,19,2,0,8
43,american_league,2026-10-11,650968,Yohel Pozo,110,29,4,9.53,2,4,...,0,0,94,9.09,3.92,.692,9,0,0,4
46,american_league,2026-10-11,665966,Jackson Holliday,110,27,36,3.75,2,11,...,4,0,731,9.46,8.25,.814,48,5,0,15
70,american_league,2026-10-11,694212,Yennier Cano,110,21,25,3.69,0,12,...,3,2,495,9.05,8.25,.739,34,1,0,16
85,american_league,2026-10-11,657136,Alec Gamboa,111,30,26,3.47,0,8,...,3,0,544,9.00,7.81,.855,47,4,0,17
90,american_league,2026-10-11,668939,Adley Rutschman,111,28,36,3.17,2,21,...,3,2,626,8.83,8.17,.661,41,5,0,20